/* This file was generated by SableCC (http://www.sablecc.org/). */

package asf.abstractcc.node;

import java.util.*;

import asf.abstractcc.analysis.*;

public final class ANullTerm extends PTerm
{

  public ANullTerm()
  {}
  public Object clone()
  {
    return new ANullTerm();
  }

  public void apply(Switch sw)
  {
    ((Analysis) sw).caseANullTerm(this);
  }

  public String toString()
  {
    return "";
  }

  void removeChild(Node child)
  {}

  void replaceChild(Node oldChild, Node newChild)
  {}
}
