/* This file was generated by SableCC (http://www.sablecc.org/). */

package asf.abstractcc.node;

import java.util.*;

import asf.abstractcc.analysis.*;

public final class ATokenSpecifier extends PSpecifier
{

  public ATokenSpecifier()
  {}
  public Object clone()
  {
    return new ATokenSpecifier();
  }

  public void apply(Switch sw)
  {
    ((Analysis) sw).caseATokenSpecifier(this);
  }

  public String toString()
  {
    return "";
  }

  void removeChild(Node child)
  {}

  void replaceChild(Node oldChild, Node newChild)
  {}
}
