/* This file was generated by SableCC (http://www.sablecc.org/). */

package asf.abstractcc.node;

import asf.abstractcc.analysis.*;

public final class THelpers extends Token
{
  public THelpers()
  {
    super.setText("Helpers");
  }

  public THelpers(int line, int pos)
  {
    super.setText("Helpers");
    setLine(line);
    setPos(pos);
  }

  public Object clone()
  {
    return new THelpers(getLine(), getPos());
  }

  public void apply(Switch sw)
  {
    ((Analysis) sw).caseTHelpers(this);
  }

  public void setText(String text)
  {
    throw new RuntimeException("Cannot change THelpers text.");
  }
}
